In [1]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
print(a)
print(type(a))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [2]:
a = np.array([10, 20, 30, 40])

print(a[0])   # 10
print(a[2])   # 30



10
30


In [5]:
print(a)
print(a.ndim)    # number of dimensions
print(a.shape)   # structure
print(a.size)    # number of elements
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.ndim)    # number of dimensions
print(b.shape)   # structure
print(b.size)    # number of elements


[10 20 30 40]
1
(4,)
4
[[1 2 3]
 [4 5 6]]
2
(2, 3)
6


1️⃣ range() – Python Built-in
What range() does

Generates numbers one by one

Mainly used in loops

Not a NumPy object

In [6]:
for i in range(5):
    print(i)



0
1
2
3
4


3️⃣ np.arange() – NumPy Version
What np.arange() does

Creates a NumPy array

Stores values in contiguous memory

Much faster for math operations

In [7]:
import numpy as np

a = np.arange(5)
print(a)


[0 1 2 3 4]


5️⃣ Start, Stop, Step (Same Idea – Different Power)
range(start, stop, step)


In [9]:
for i in range(2, 10, 2):
    print(i)

import numpy as np
np.arange(2, 10, 2)


2
4
6
8


array([2, 4, 6, 8])

In [10]:
np.arange(10, 2, -2)


array([10,  8,  6,  4])

🔹 Step-by-Step Visualization (IMPORTANT)

Range = 10 - 0 = 10

You want 5 numbers

So spacing = 10 ÷ (5 - 1) = 2.5

Numbers become:

0
0 + 2.5 = 2.5
2.5 + 2.5 = 5
5 + 2.5 = 7.5
7.5 + 2.5 = 10


✔ Even spacing
✔ End included

In [11]:
import numpy as np

x = np.linspace(0, 10, 5)
print(x)


[ 0.   2.5  5.   7.5 10. ]


In [ ]:
import numpy as np

x = np.array([1, 2, 3, 4, 5, 6])
print(x)

y = x.reshape(2, 3)
print(y)


print(y.reshape(3, 2))

z = np.array([[1, 2, 3],
              [4, 5, 6]])

print(z.flatten())


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


3️⃣ np.zeros() – Create arrays filled with zero
1D array
a = np.zeros(5)
print(a)


Output:

[0. 0. 0. 0. 0.]

2D array
a = np.zeros((2, 3))
print(a)


Output:

[[0. 0. 0.]
 [0. 0. 0.]]

Integer zeros
a = np.zeros((2, 3), dtype=int)
print(a)


📌 Used for:

Initialization

Placeholders

Matrices

4️⃣ np.ones() – Same as zeros, but filled with 1
a = np.ones((3, 4))
print(a)


Output:

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

5️⃣ np.full() – Fill with ANY value
a = np.full((2, 3), 7)
print(a)


Output:

[[7 7 7]
 [7 7 7]]


In [ ]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])

#Access a single element 
a[0]   # 10
a[2]   # 30
a[4]   # 50

#Negative indexing 

a[-1]   # 50 (last element)
a[-2]   # 40

#Slicing in 1D
#array[start : stop : step]

a[1:4]      # [20 30 40]
a[:3]       # [10 20 30]
a[2:]       # [30 40 50]
a[::2]      # [10 30 50]


#Indexing in 2D arrays
b = np.array([
    [1,  2,  3],
    [4,  5,  6],
    [7,  8,  9]
])

#Row 0 → [1  2  3]
#Row 1 → [4  5  6]
#Row 2 → [7  8  9]

#Accesing elements in 2D array
b[0, 0]   # 1
b[0, 2]   # 3
b[1, 1]   # 5
b[2, 0]   # 7

#Access Entire Rows or Columns
b[0, :]    # First row → [1  2  3]
b[:, 0]    # First column → [1  4  7]


np.int64(40)

In [ ]:
#Slicing in 2D arrays
b[0:2, 1:3]   # Rows 0-1 and Columns 1-2 → [[2  3]
               #                                 [5  6]]

               

8️⃣ Axis Concept (Very Important)
Axis	Meaning
axis = 0	Column-wise (top → bottom)
axis = 1	Row-wise (left → right)

In [ ]:
np.sum(b, axis=0)  # Column sums
np.sum(b, axis=1)  # Row sums


In [14]:
import numpy as np

a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
b = np.array([
    [7, 8, 9],
    [10, 11, 12]
])

print(a.T)
print(b.T)


[[1 4]
 [2 5]
 [3 6]]
[[ 7 10]
 [ 8 11]
 [ 9 12]]
